
CREATE TABLE IF NOT EXISTS  `bank_account` (
  `ACCOUNT_ID` varchar(100) DEFAULT NULL,
  `BALANCE` NUMERIC DEFAULT NULL,
  `CLIENT_NAME` varchar(100) DEFAULT NULL,
  `CREATION_DATE` date DEFAULT current_timestamp(),
  PRIMARY KEY (`ACCOUNT_ID`)
);

CREATE TABLE IF NOT EXISTS  `transaction` (
  `TRANSACTION_ID` varchar(100) DEFAULT NULL,
  `AMOUNT` NUMERIC DEFAULT NULL,
  `TRANSACTION_DATE` date DEFAULT current_timestamp(),
  `TYPE` varchar(100) DEFAULT NULL,
  `ACCOUNT_ID` varchar(100) DEFAULT NULL,
  foreign key (ACCOUNT_ID) references bank_account(ACCOUNT_ID),
  PRIMARY KEY (`TRANSACTION_ID`)
);
--
--ALTER TABLE transaction
--ADD CONSTRAINT fk_BANK_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES bank_account (ACCOUNT_ID);

INSERT INTO bank_account (ACCOUNT_ID, BALANCE, CLIENT_NAME, CREATION_DATE ) VALUES ( '1', 0, 'ADMIN', '2025-01-09');
INSERT INTO bank_account (ACCOUNT_ID, BALANCE, CLIENT_NAME, CREATION_DATE ) VALUES ( '2', 0, 'KATA', '2025-01-09');

INSERT INTO transaction (TRANSACTION_ID, AMOUNT, TYPE, ACCOUNT_ID) VALUES ( '0e8328c1-0127-49fa-8b83-a0d4e14ebecd', 150, 'DEPOSIT', '1');
INSERT INTO transaction (TRANSACTION_ID, AMOUNT, TYPE, ACCOUNT_ID) VALUES ( '0e8328c1-0127-49fa-8b83-a0d4e14ebecf', 48, 'DEPOSIT', '1');
INSERT INTO transaction (TRANSACTION_ID, AMOUNT, TYPE, ACCOUNT_ID) VALUES ( '0e8328c1-0127-49fa-8b83-a0d4e14ebecg', 56.69, 'WITHDRAWAL', '1');