server:
  port: 8081
spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:tcp://localhost:9090/mem:bank-account
    driverClassName: org.h2.Driver
    username: kata-sg
    password: kata-sg
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect