server:
  port: 8080
spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:bank-account
    driverClassName: org.h2.Driver
    username: kata-sg
    password: kata-sg
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

#    url: jdbc:h2:file:~/bank-account;DB_CLOSE_DELAY=-1
